<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosClient;
use heyAuto\DemoBundle\Entity\PosInvoice;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosCategoryRepository extends EntityRepository
{
	public function getAllCategory($companyCode, $language_code){
		 $sql = "SELECT  
				  cate.category_id, lg.lng_value, cate.description , cate.create_time,
				  cate.update_time, cate.flag, cate.parent_id
				FROM pos_category AS cate 
				INNER JOIN pos_language_cate lg on lg.category_id = cate.category_id 
				WHERE company_code = '".$companyCode."' AND lg.lng_code='".$language_code."'
				";
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
		$stmt->execute();
		return $stmt->fetchAll();
	}

	
}
