<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosClient;
use heyAuto\DemoBundle\Entity\PosInvoice;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosClientRepository extends EntityRepository
{
	public function findClientByPhone($phone)
	{
		return $this->getEntityManager()->getRepository('heyAutoDemoBundle:PosClient')->findOneBy(array('phone' => $phone));
	}

	public function getPosClientByinvoice($invoiceCode)
	{
		return $this->getEntityManager()
		->createQuery(
				" SELECT cl
					FROM heyAutoDemoBundle:PosClient cl
					INNER JOIN heyAutoDemoBundle:PosInvoice inv WITH cl.client_id = inv.client_id
					WHERE inv.inv_code = '".$invoiceCode."'
				"
		)->getResult();
	}

	public function getPosClientByPhone($phoneNumber, $companyCode)
	{
		return $this->getEntityManager()
		->createQuery(
				" SELECT cl
					FROM heyAutoDemoBundle:PosClient cl
					WHERE cl.phone = '".$phoneNumber."'
					AND cl.company_code = '".$companyCode."'
				"
		)->getResult();
	}

	public function createNewPosClient(PosClient $posClient) 
	{
		
		if($posClient == null) {
			return 2;
			
		} else {
			if($posClient->getPhone() != null && $this->findClientByPhone($posClient->getPhone()) != null){
				return 2;
			}
			
			$manager = $this->getEntityManager();
			$manager->persist($posClient);
			$manager->flush();
			$posClient ->setClientId ($posClient->getClientId());
			
			return 1;
			
		}
	}

	
}
