<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosClient;
use heyAuto\DemoBundle\Entity\PosInvoice;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosClientRepository extends EntityRepository
{


	public function getPosClientByinvoice($invoiceCode)
	{
		return $this->getEntityManager()
		->createQuery(
				" SELECT cl
					FROM heyAutoDemoBundle:PosClient cl
					INNER JOIN heyAutoDemoBundle:PosInvoice inv WITH cl.client_id = inv.client_id
					WHERE inv.inv_code = '".$invoiceCode."'
				"
		)->getResult();

		// return $this->getEntityManager()->createQueryBuilder()
		// 	->select('c', 'inv')
		//     ->from('heyAuto\DemoBundle\Entity\PosClient', 'c')
		//     ->innerJoin('c', 'heyAuto\DemoBundle\Entity\PosInvoice', 'inv', 'c.client_id = inv.client_id') ->getQuery()->getResult();
	}

	public function createNewPosClient(PosClient $posClient) 
	{
		
		if($posClient == null) {
			return array (
					'mSuccess' => false,
					'mErrorField' => null,
					'mMessage' => "Unknown error" 
			);
			
		} else {
			
			$manager = $this->getEntityManager();
			$manager->persist($posClient);
			$manager->flush();
			$posClient ->setClientId ($posClient->getClientId());
			
			return array (
						'mSuccess' => true,
						'mErrorField' => null,
						'mMessage' => "Registration succeded"
			);
			
		}
	}

	
}
