<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosCookItem;
use heyAuto\DemoBundle\Entity\PosGroupMobile;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosCookItemRepository extends EntityRepository
{


	public function getAllCookItem($item_id, $user_id, $companyCode){
		 $sql = "SELECT id, item_id, user_id, quantity, cook_createtime, cook_updatetime, notes, checked 
				 FROM pos_cookitem 
				 WHERE company_code = '".$companyCode."' 
				 AND item_id = '".$item_id."' 
				 AND user_id = '".$user_id."' 
				 AND checked = '1' 
				 and convert(date,cook_createtime)=convert(date,getdate())
				";
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
		$stmt->execute();
		return $stmt->fetchAll();
	}

	public function getCookItem($companyCode){
		 $sql = "SELECT inv_d.item_id,  sum(inv_d.quantity) as total, it.name
				FROM pos_cookitem  AS inv_d				
				INNER JOIN pos_items it ON it.item_id = inv_d.item_id					
				WHERE inv_d.company_code = '".$companyCode."' AND it.company_code = '".$companyCode."' 
				AND inv_d.checked = '1' 
				AND CONVERT(VARCHAR(20),inv_d.cook_createtime, 112) >= CONVERT(VARCHAR(20),GETDATE(), 112)
				GROUP BY inv_d.item_id,  it.name
				";
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
		$stmt->execute();
		return $stmt->fetchAll();
	}

	public function createNewPosCookeItem(PosCookItem $posCookItem) 
	{
		
		if($posCookItem == null) {
			return array (
					'mSuccess' => false,
					'mErrorField' => null,
					'mMessage' => "Unknown error" 
			);
			
		} else {
			
			$manager = $this->getEntityManager();
			$manager->persist($posCookItem);
			$manager->flush();
			
			return array (
						'mSuccess' => true,
						'mErrorField' => null,
						'mMessage' => "Registration succeded"
			);
			
		}
	}
	
}
