<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosUsers;
use heyAuto\DemoBundle\Entity\PosGroupMobile;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosGroupMobileRepository extends EntityRepository
{
	
	public function getTitleForUser($userName, $password, $companyCode) {
		return $this->getEntityManager()
		->createQuery(
				"select gm.title from heyAutoDemoBundle:PosGroupMobile gm WHERE gm.id = 
				(select ugm.group_mobile_id from heyAutoDemoBundle:PosUserGroupMap ugm where ugm.user_id = 
				(select u.id from heyAutoDemoBundle:PosUsers u where u.username = '".$userName."' and u.password = '".$password."' and u.company_code = '".$companyCode."'))"
		)->getResult();
	}
}
