<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosItemCost;
use heyAuto\DemoBundle\Entity\PosInvoice;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosItemCostRepository extends EntityRepository
{


	public function getIdPosItemCost( $company_code)
	{
		return $this->getEntityManager()
		->createQuery(
				" SELECT ic FROM heyAutoDemoBundle:PosItemCost ic 
				  WHERE ic.company_code = '".$company_code."' 
				  ORDER BY ic.end_date DESC
				"
		)->getResult();
	}

	
}
