<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosInvoice;
use heyAuto\DemoBundle\Entity\PosGroupMobile;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosInvoiceRepository extends EntityRepository
{
	
	public function getNumberRowForInvoice($companyCode) {
		return $this->getEntityManager()
		->createQuery(
				"SELECT inv
					FROM heyAutoDemoBundle:PosInvoice inv
					WHERE inv.company_code = '".$companyCode."'
					AND convert(varchar, inv.inv_starttime, 105) >= convert(varchar, getdate(), 105)
					AND inv.status != 3
					ORDER BY CASE inv.status WHEN 1 THEN 1 
											 WHEN 3 THEN 2
											 WHEN 0 THEN 3 
											 WHEN 2 THEN 4  
							 END, inv.inv_id DESC
				"
		)->getResult();
	}

	public function updateInvoiceByInvoiceCode(PosInvoice $posInvoice) {

		$manager = $this->getEntityManager();
		$manager->merge($posInvoice);
		$manager->flush();

		return array (
						'mSuccess' => true,
						'mErrorField' => null,
						'mMessage' => "User updated successfully"
				);
		
	}

	public function findInvoiceIdByInvoiceCode($invCode, $companyCode)
	{
		// return $this->getEntityManager()->getRepository('heyAutoDemoBundle:PosInvoice')
		// 	->findOneBy(array('inv_code' => $invCode, 'company_code' => $companyCode));
		return $this->getEntityManager()
		->createQuery(
				" SELECT g
					FROM heyAutoDemoBundle:PosInvoice g
					WHERE g.inv_code = '".$invCode."' 
					AND g.company_code = '".$companyCode."' 
				"
		)->getResult();
	}
}
