<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosItems;
use heyAuto\DemoBundle\Entity\PosMediaItems;
use heyAuto\DemoBundle\Entity\PosLanguageItem;
use heyAuto\DemoBundle\Entity\PosItemCostDetail;
use heyAuto\DemoBundle\Entity\PosCategory;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosItemsRepository extends EntityRepository
{


	public function getInfoPosItems( $itemCostId, $cate_name, $cate_id, $language_code, $company_code)
	{
		return $this->getEntityManager()
		->createQuery(
				"  SELECT DISTINCT it, it_c_dt, m
				FROM heyAutoDemoBundle:PosItems AS it  
				INNER JOIN heyAutoDemoBundle:PosMediaItems md_it WITH md_it.items_id = it.item_id 
				INNER JOIN heyAutoDemoBundle:PosLanguageItem lg WITH lg.item_id = it.item_id 
				INNER JOIN heyAutoDemoBundle:PosItemCostDetail it_c_dt WITH it_c_dt.items_cost_id = '".$itemCostId."'
				INNER JOIN heyAutoDemoBundle:PosCategory pc WITH it.category_id = pc.category_id
				INNER JOIN heyAutoDemoBundle:PosMediaItems mi WITH mi.items_id = md_it.items_id
				INNER JOIN heyAutoDemoBundle:PosMedia m WITH m.media_id = mi.media_id
				WHERE it.company_code ='".$company_code."'
				AND it.item_id = it_c_dt.item_id
				AND pc.parent_id = '".$cate_id."'
				AND lg.lng_value like '%".$cate_name."%'
				AND lg.lng_code='".$language_code."'
				ORDER BY it.item_id ASC
				"
		)->getResult();
	}

	public function getAllParentItemPosItems( $itemCostId, $cate_id, $dateNow, $company_code)
	{
		return $this->getEntityManager()
		->createQuery(
				"  SELECT DISTINCT it, it_c_dt, m
				FROM heyAutoDemoBundle:PosItems AS it  
				INNER JOIN heyAutoDemoBundle:PosMediaItems md_it WITH md_it.items_id = it.item_id 
				INNER JOIN heyAutoDemoBundle:PosLanguageItem lg WITH lg.item_id = it.item_id 
				INNER JOIN heyAutoDemoBundle:PosItemCostDetail it_c_dt WITH it_c_dt.items_cost_id = '".$itemCostId."'
				INNER JOIN heyAutoDemoBundle:PosItemCost it_c WITH it_c_dt.items_cost_id = it_c.id
				INNER JOIN heyAutoDemoBundle:PosCategory pc WITH it.category_id = pc.category_id
				INNER JOIN heyAutoDemoBundle:PosMediaItems mi WITH mi.items_id = md_it.items_id
				INNER JOIN heyAutoDemoBundle:PosMedia m WITH m.media_id = mi.media_id
				WHERE it.company_code ='".$company_code."'
				AND it.item_id = it_c_dt.item_id
				AND pc.parent_id = '".$cate_id."'
				AND  it_c.start_date < '".$dateNow."'
				AND '".$dateNow."' < it_c.end_date
				ORDER BY it.item_id ASC
				"

		)->getResult();
	}


	
}
