<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosItemCost;
use heyAuto\DemoBundle\Entity\PosItemCostDetail;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosItemCostDetailRepository extends EntityRepository
{


	public function getPriceItemCostDetail( $itemCostId, $company_code)
	{
		return $this->getEntityManager()
		->createQuery(
				" SELECT it_c_d FROM heyAutoDemoBundle:PosInvoiceDetail inv 
				  INNER JOIN heyAutoDemoBundle:PosItemCostDetail it_c_d WITH it_c_d.items_cost_id = '".$itemCostId."'
				  INNER JOIN heyAutoDemoBundle:PosItems it WITH it.item_id = it_c_d.item_id 
				  INNER JOIN heyAutoDemoBundle:PosLanguageItem lng WITH lng.item_id = it.item_id
				  WHERE inv.company_code='".$company_code."'
				  		AND inv.item_id = it.item_id
				"
		)->getResult();
	}

	
}
