<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosInvoice;
use heyAuto\DemoBundle\Entity\PosGroupMobile;
use heyAuto\DemoBundle\Entity\PosUserGroupMap;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosInvoiceRepository extends EntityRepository
{
	
	public function getNumberRowForInvoice($companyCode) {
		return $this->getEntityManager()
		->createQuery(
				"SELECT inv
					FROM heyAutoDemoBundle:PosInvoice inv
					WHERE inv.company_code = '".$companyCode."'
					AND convert(varchar, inv.inv_starttime, 105) >= convert(varchar, getdate(), 105)
					AND inv.status != 3
					ORDER BY CASE inv.status WHEN 1 THEN 1 
											 WHEN 3 THEN 2
											 WHEN 0 THEN 3 
											 WHEN 2 THEN 4  
							 END, inv.inv_id DESC
				"
		)->getResult();
	}
}
