<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosItemCostDetail;
use heyAuto\DemoBundle\Entity\PosItems;
use heyAuto\DemoBundle\Entity\PosLanguageItem;
use heyAuto\DemoBundle\Entity\PosInvoiceDetail;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosInvoiceDetailRepository extends EntityRepository
{


	public function getInvoiceDetail($itemCostId, $company_code)
	{
		return $this->getEntityManager()
		->createQuery(
				" SELECT inv FROM heyAutoDemoBundle:PosInvoiceDetail inv 
				  INNER JOIN heyAutoDemoBundle:PosItemCostDetail it_c_d WITH it_c_d.items_cost_id = '".$itemCostId."'
				  INNER JOIN heyAutoDemoBundle:PosItems it WITH it.item_id = it_c_d.item_id 
				  INNER JOIN heyAutoDemoBundle:PosLanguageItem lng WITH lng.item_id = it.item_id
				  WHERE inv.company_code='".$company_code."'
				  		AND inv.item_id = it.item_id
				"
		)->getResult();
	}

	public function deleteInvoice($company_code, $inv_code, $item_id) 
	{
		return $this->getEntityManager()
		->createQuery("DELETE FROM pos_invoice_detail where company_code = '$company_code' AND inv_code ='".$inv_code."' and item_id ='".$item_id."'")->getResult();	
	}
}
