<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosMediaItem;
use heyAuto\DemoBundle\Entity\PosStageITable;
use heyAuto\DemoBundle\Entity\PosStage;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosMediaItemRepository extends EntityRepository
{
	public function findIdMediaItem($items_id)
	{
		return $this->getEntityManager()->getRepository('heyAutoDemoBundle:PosMediaItem')->findBy(
			array('items_id' => $items_id)
		);
	}

}
