<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosMedia;
use heyAuto\DemoBundle\Entity\PosStageITable;
use heyAuto\DemoBundle\Entity\PosStage;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;



/**
 * PosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosMediaRepository extends EntityRepository
{
	public function findNameMedia($media_id, $company_code)
	{
		return $this->getEntityManager()->getRepository('heyAutoDemoBundle:PosMedia')->findBy(
			array('media_id' => $media_id, 'company_code'=> $company_code)
		);
	}

	public function getAllMedia($itemId, $companyCode){
		 $sql = "SELECT name FROM pos_media 
		 		WHERE company_code = '".$companyCode."'
		 		AND media_id IN (SELECT media_id FROM pos_media_items WHERE items_id = '".$itemId."')
				";
		$stmt = $this->getEntityManager()->getConnection()->prepare($sql);
		$stmt->execute();
		return $stmt->fetchAll();
	}
	
	
}
