<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosStageITable;

/**
 * PosStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosStageITableRepository extends EntityRepository
{
	public function createNewPosITableStage(PosStageITable $posStageItable) 
	{
		
		if($posStageItable == null) {
			return array (
					'mSuccess' => false,
					'mErrorField' => null,
					'mMessage' => "Unknown error" 
			);
			
		} else {
			
			$manager = $this->getEntityManager();
			$manager->persist($posStageItable);
			$manager->flush();
			
			return array (
						'mSuccess' => true,
						'mErrorField' => null,
						'mMessage' => "Registration succeded"
			);
			
		}
	}

	public function deleteItableInStage($itableId) {
		return $this->getEntityManager()
		->createQuery(
				" DELETE FROM heyAutoDemoBundle:PosStageITable tb
					WHERE tb.id_itable = '".$itableId."' 
				"
		)->getResult();
	}
}
