<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\PosVoice;
use Symfony\Component\Validator\Constraints\EqualTo;
use Monolog\Logger;

/**
 * PosStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosVoiceRepository extends EntityRepository
{
	public function getVoicebyCompanyCode($companyCode) {
		return $this->getEntityManager()
		->createQuery(
				"SELECT p
					FROM heyAutoDemoBundle:PosVoice p
					WHERE p.company_code = '".$companyCode."' "
		)->getResult();

	}


}
