<?php

namespace heyAuto\DemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use heyAuto\DemoBundle\Entity\Vehicle;
use Monolog\Logger;
use Symfony\Bridge\Monolog\Handler\ConsoleHandler;


/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends EntityRepository
{

	public function updateVehicle(Vehicle $vehicle) {
		
		$manager = $this->getEntityManager();
		$manager->merge($vehicle);
		$manager->flush();
		
		return array (
				'mSuccess' 		=> true,
				'mErrorField' 	=> null,
				'mMessage' 		=> "Vehicle updated successfully"
			);
		
	}
}
